DROP DATABASE IF EXISTS projectB;

CREATE DATABASE projectB;
USE projectB;

-- uncomment the comment below and copy it before each table to drop an existing table
-- DROP TABLE IF EXISTS TABLENAME 
CREATE TABLE UserAccount(
UserID		INT	NOT NULL AUTO_INCREMENT,
UserEmail	VARCHAR(255)		NOT NULL,

FirstName	VARCHAR(25)		NOT NULL,
LastName	VARCHAR(25)		NOT NULL,
Phone		CHAR(10),
Password	VARCHAR(2048)		NOT NULL,
TimeStamp	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

PRIMARY KEY(UserID),
UNIQUE (UserEmail)
);

-- Table: Roles
CREATE TABLE Roles (
RoleID	INT	NOT NULL AUTO_INCREMENT,
TimeStamp	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
roleType		VARCHAR(16),
PRIMARY KEY (RoleID)
);


-- Table: Address
CREATE TABLE Address (
AddressID	INT			NOT NULL AUTO_INCREMENT,
ZipCode		CHAR(5)			NOT NULL,
TimeStamp	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
StreetAddress	VARCHAR(50),
State CHAR(2),
PRIMARY KEY (AddressID)
);

-- Table: Employer
CREATE TABLE Employer (
EmployerID	INT	NOT NULL	UNIQUE AUTO_INCREMENT,
UserID		INT,
AddressID	INT,
TimeStamp	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
EmployerEmail	VARCHAR(255)	NOT NULL,
EmployerName	VARCHAR(50)	NOT NULL,
EmployerPhone	CHAR(11),
HiringRoleId		INT,
PRIMARY KEY (EmployerID),
FOREIGN KEY (HiringRoleId) REFERENCES Roles(RoleID),
FOREIGN KEY (UserID) REFERENCES UserAccount(UserID),
FOREIGN KEY (AddressID) REFERENCES Address(AddressID)
);



CREATE TABLE EducationLevels (
EducationID	INT	NOT NULL AUTO_INCREMENT,
TimeStamp	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
EducationLevel		VARCHAR(16),
PRIMARY KEY (EducationID)
);


-- Table: Employee
CREATE TABLE Employee (
EmployeeID		INT NOT NULL AUTO_INCREMENT,
UserID			INT	NOT NULL,
EducationLevel	INT	NOT NULL,
TimeStamp	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (EmployeeID),
FOREIGN KEY (UserID) REFERENCES UserAccount (UserID),
FOREIGN KEY (EducationLevel) REFERENCES EducationLevels (EducationID)
);


-- Table: JobTypes
CREATE TABLE JobTypes (
JobTypeID	INT	NOT NULL AUTO_INCREMENT,
TimeStamp	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
JobType		VARCHAR(16),
PRIMARY KEY (JobTypeID)
);

-- Table: ExpereinceRequired
CREATE TABLE ExperienceRequired (
ExpReqID	INT	NOT NULL AUTO_INCREMENT,
TimeStamp	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
ExpType		VARCHAR(50),
PRIMARY KEY (ExpReqID)
);

-- Table: SalaryRange
CREATE TABLE SalaryRange (
SalaryID	INT	NOT NULL AUTO_INCREMENT,
TimeStamp	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
Salary		INT,
PRIMARY KEY (SalaryID)
);

-- Table: JobPosts
CREATE TABLE JobPosts (
JobPostID	INT	NOT NULL AUTO_INCREMENT,
EducationID	INT	NOT NULL,
AddressID	INT	NOT NULL,
JobTypeID	INT	NOT NULL,
ExpReqID	INT	NOT NULL,
SalaryID	INT	NOT NULL,

TimeStamp	TIMESTAMP,
JobPostTitle		CHAR(30),
JobDescription	VARCHAR(200),
Responsibilities	VARCHAR(200),
Qualifications	VARCHAR(200),
DatePosted	DATE,
Deadline	DATE,
ContactDetails	INT,

PRIMARY KEY (JobPostID),
FOREIGN KEY (EducationID) REFERENCES EducationLevels (EducationID),
FOREIGN KEY (AddressID) REFERENCES Address (AddressID),
FOREIGN KEY (JobTypeID) REFERENCES JobTypes (JobTypeID),
FOREIGN KEY (ExpReqID) REFERENCES ExperienceRequired (ExpReqID),
FOREIGN KEY (SalaryID) REFERENCES SalaryRange (SalaryID),
FOREIGN KEY (ContactDetails) REFERENCES Employer (EmployerID)

);


-- Table: EmployerPosts
CREATE TABLE EmployerPosts (
EmployerID	INT	NOT NULL ,
JobPostID	INT	NOT NULL,
TimeStamp	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (JobPostID),
FOREIGN KEY (EmployerID) REFERENCES Employer (EmployerID),
FOREIGN KEY (JobPostID)  REFERENCES JobPosts (JobPostID)
);


-- Table: SavedPosts
CREATE TABLE SavedPosts (
EmployeeID	INT	NOT NULL,
JobPostID	INT	NOT NULL,
TimeStamp	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (EmployeeID,JobPostID),
FOREIGN KEY (EmployeeID) REFERENCES Employee (EmployeeID),
FOREIGN KEY (JobPostID)  REFERENCES JobPosts (JobPostID)
);


-- Table: ApplicationStatus
CREATE TABLE ApplicationStatus (
AppStatusID	INT	NOT NULL AUTO_INCREMENT,
TimeStamp	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
AppStatus	VARCHAR(16),
PRIMARY KEY (AppStatusID)
);

-- Table: AppliedPosts
CREATE TABLE AppliedPosts (
EmployeeID	INT	NOT NULL,
AppStatusID	INT	NOT NULL,
JobPostID	INT	NOT NULL,
TimeStamp	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (EMployeeID,AppStatusID,JobPostID),
FOREIGN KEY (EmployeeID)  REFERENCES Employee (EmployeeID),
FOREIGN	KEY (AppStatusID) REFERENCES ApplicationStatus (AppStatusID),
FOREIGN KEY (JobPostID)   REFERENCES JobPosts (JobPostID)
);


-- Table: BenefitsOffered
CREATE TABLE BenefitsOffered (
BenefitID	INT	NOT NULL AUTO_INCREMENT,
TimeStamp	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
BenefitType		VARCHAR(20),
PRIMARY KEY (BenefitID)
);


-- Table: JobBenefits
CREATE TABLE JobBenefits (
BenefitID	INT	NOT NULL,
JobPostID	INT	NOT NULL,
TimeStamp	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (BenefitID,JobPostID),
FOREIGN KEY (BenefitID)	REFERENCES BenefitsOffered(BenefitID),
FOREIGN KEY (JobPostID)	REFERENCES JobPosts (JobPostID)
);
